media: 
  input: public/images/projects
  output: /images/projects
content:
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    view:
      fields: [title, published, order]
    fields:
      - name: title
        label: Title
        type: string
      
      - name: skills
        label: Skills
        type: list
        items:
          type: string
      
      - name: image
        label: Image
        type: image
        description: Path to the project image
      
      - name: link
        label: Project Link
        type: string
        description: External link to the project (optional)
      
      - name: order
        label: Display Order
        type: number
        description: Order in which the project appears
      
      - name: published
        label: Published
        type: boolean
        default: false
      
      - name: github
        label: GitHub Repository
        type: string
        description: Link to GitHub repository (optional)